services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./data:/app/data
      - ./next.config.ts:/app/next.config.ts
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: unless-stopped

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
